### ISSUE TITLE
Help please. I tried serveral bepinEX versions (from 5.4.19 to 5.4.23),but all of them cannot work and get the following error.

### ISSUE THREAD

**Issue by Hatsukano** [qinyan-alpha/KK-osr2-sr6-link#1]
[Error  : Unity Log] MissingMethodException: Method not found: 'Timeline.Timeline.Seek'.

Anyway to resolve this?

**Comment by Hatsukano** [comment]
This error turns out when I opened koikatsu studio without doing anything.

**Comment by Hatsukano** [comment]
Worked after downloading Koikatsu better pack RX21

**Comment by qinyan-alpha** [comment]
Please update the timeline to the latest version.
